import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'pdf_search_project.settings')
django.setup()

def column_exists(table, column):
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT 1 
            FROM information_schema.columns 
            WHERE table_name=%s AND column_name=%s
        """, [table, column])
        return bool(cursor.fetchone())

def table_exists(table):
    with connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM information_schema.tables WHERE table_name = %s", [table])
        return bool(cursor.fetchone())

with connection.cursor() as cursor:
    print("🔧 Iniciando reparación de base de datos (Modo Robusto v2)...")

    # 1. Crear tabla 'download_log' si falta
    if not table_exists('download_log'):
        print("1. Creando tabla 'download_log'...")
        cursor.execute("""
            CREATE TABLE download_log (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                filename VARCHAR(500) NOT NULL,
                downloaded_at TIMESTAMP WITH TIME ZONE NOT NULL,
                ip_address INET NULL,
                user_id BIGINT NULL REFERENCES users(id)
            );
        """)
        cursor.execute("CREATE INDEX download_log_user_id_idx ON download_log(user_id);")
    else:
        print("1. Tabla 'download_log' ya existe. Saltando.")

    # 2. Asegurar columnas nuevas en 'pdf_index'
    print("2. Verificando columnas en 'pdf_index'...")
    
    # Lista de columnas a verificar y sus definiciones
    columns_to_check = [
        ('md5_hash', 'VARCHAR(64)'),
        ('last_modified', 'TIMESTAMP WITH TIME ZONE DEFAULT NOW()'),
        ('is_indexed', 'BOOLEAN DEFAULT TRUE'),
        ('codigos_empleado', "TEXT DEFAULT ''"),
        ('size_bytes', 'BIGINT DEFAULT 0')
    ]

    for col_name, col_def in columns_to_check:
        if not column_exists('pdf_index', col_name):
            print(f"   - Agregando columna: {col_name}")
            cursor.execute(f"ALTER TABLE pdf_index ADD COLUMN {col_name} {col_def};")
        else:
            print(f"   - Columna '{col_name}' ya existe. OK.")

    # 3. Restricción UNIQUE
    # Intentamos agregarla, si falla asumimos que ya está.
    try:
        cursor.execute("ALTER TABLE pdf_index ADD CONSTRAINT pdf_index_minio_object_name_key UNIQUE (minio_object_name);")
        print("   - Restricción UNIQUE añadida.")
    except Exception:
        print("   - (Nota: Restricción UNIQUE ya existía)")

    print("\n✅ Reparación completada. Ahora ejecuta:\n   python manage.py migrate documents 0001 --fake")
