import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'pdf_search_project.settings')
django.setup()

def table_exists(table):
    with connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM information_schema.tables WHERE table_name = %s", [table])
        return bool(cursor.fetchone())

with connection.cursor() as cursor:
    print("🔧 Reparando tablas M2M de usuarios faltantes...")

    # 1. Crear 'users_groups' (Necesario para auth groups)
    # Segun tu log de error, Django la busca como 'users_groups'
    if not table_exists('users_groups'):
        print("   - Creando tabla 'users_groups'...")
        cursor.execute("""
            CREATE TABLE users_groups (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customuser_id BIGINT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
                group_id INTEGER NOT NULL REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED
            );
        """)
        cursor.execute("CREATE INDEX users_groups_customuser_id_idx ON users_groups(customuser_id);")
        cursor.execute("CREATE INDEX users_groups_group_id_idx ON users_groups(group_id);")
        # Unique constraint
        cursor.execute("ALTER TABLE users_groups ADD CONSTRAINT users_groups_customuser_id_group_id_uniq UNIQUE (customuser_id, group_id);")
    else:
        print("   - Tabla 'users_groups' ya existe.")

    # 2. Crear 'users_user_permissions' (Necesario para permisos especificos)
    if not table_exists('users_user_permissions'):
        print("   - Creando tabla 'users_user_permissions'...")
        cursor.execute("""
            CREATE TABLE users_user_permissions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customuser_id BIGINT NOT NULL REFERENCES users(id) DEFERRABLE INITIALLY DEFERRED,
                permission_id INTEGER NOT NULL REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED
            );
        """)
        cursor.execute("CREATE INDEX users_user_permissions_customuser_id_idx ON users_user_permissions(customuser_id);")
        cursor.execute("CREATE INDEX users_user_permissions_permission_id_idx ON users_user_permissions(permission_id);")
        # Unique constraint
        cursor.execute("ALTER TABLE users_user_permissions ADD CONSTRAINT users_user_permissions_cu_pid_uniq UNIQUE (customuser_id, permission_id);")
    else:
        print("   - Tabla 'users_user_permissions' ya existe.")

    print("\n✅ Reparación de tablas completada. Ahora puedes ejecutar 'python manage.py migrate' de nuevo.")
