# Generated by Django 5.1.15 on 2026-04-17 15:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500)),
                ('source_path_legacy', models.CharField(blank=True, db_index=True, max_length=700)),
                ('content_hash_sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('source_hash_md5', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalogs.catalogcompany')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docrepo_documents_created', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalogs.catalogdomain')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalogs.catalogperiod')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalogs.catalogdocumentstatus')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docrepo_documents_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'docrepo_document',
            },
        ),
        migrations.CreateModel(
            name='ConstanciaAbonoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payroll_type', models.CharField(blank=True, max_length=80)),
                ('payment_batch_ref', models.CharField(blank=True, max_length=120)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('source_period_text', models.CharField(blank=True, max_length=80)),
                ('ingestion_channel', models.CharField(blank=True, max_length=50)),
                ('legacy_tipo_documento', models.CharField(blank=True, max_length=300)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='constancia_documents', to='catalogs.catalogbank')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constancia_detail', to='docrepo.document')),
            ],
            options={
                'db_table': 'docrepo_constancia_abono_document',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_code', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('EXTRACTED', 'Extracted'), ('MANUAL', 'Manual'), ('IMPORTED', 'Imported')], default='EXTRACTED', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_codes', to='docrepo.document')),
            ],
            options={
                'db_table': 'docrepo_employee_code',
            },
        ),
        migrations.CreateModel(
            name='IndexState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_indexed', models.BooleanField(default=False)),
                ('index_version', models.CharField(default='v1', max_length=40)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_by_job_id', models.UUIDField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('last_error_detail', models.TextField(blank=True)),
                ('extracted_codes_count', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index_state', to='docrepo.document')),
            ],
            options={
                'db_table': 'docrepo_index_state',
            },
        ),
        migrations.CreateModel(
            name='InsuranceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_number', models.CharField(blank=True, max_length=80)),
                ('coverage_start', models.DateField(blank=True, null=True)),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('insured_count', models.PositiveIntegerField(default=0)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_detail', to='docrepo.document')),
                ('insurance_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalogs.cataloginsurancesubtype')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='catalogs.cataloginsurancetype')),
            ],
            options={
                'db_table': 'docrepo_insurance_document',
            },
        ),
        migrations.CreateModel(
            name='StorageObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket_name', models.CharField(max_length=120)),
                ('object_key', models.CharField(max_length=800)),
                ('object_version', models.CharField(blank=True, max_length=255)),
                ('etag', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(default='application/pdf', max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_object', to='docrepo.document')),
            ],
            options={
                'db_table': 'docrepo_storage_object',
            },
        ),
        migrations.CreateModel(
            name='TRegistroDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_document_type', models.CharField(default='DNI', max_length=20)),
                ('worker_document_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tregistro_detail', to='docrepo.document')),
                ('movement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tregistro_documents', to='catalogs.catalogtregistrotype')),
            ],
            options={
                'db_table': 'docrepo_tregistro_document',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['domain', 'company', 'period'], name='docrepo_doc_dom_comp_per_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_active', 'indexed_at'], name='docrepo_doc_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash_sha256__isnull', False), models.Q(('content_hash_sha256', ''), _negated=True)), fields=('domain', 'company', 'period', 'content_hash_sha256'), name='docrepo_doc_hash_scope_uniq'),
        ),
        migrations.AddIndex(
            model_name='constanciaabonodocument',
            index=models.Index(fields=['bank', 'payroll_type'], name='docrepo_const_bank_pay_idx'),
        ),
        migrations.AddIndex(
            model_name='employeecode',
            index=models.Index(fields=['employee_code'], name='docrepo_emp_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeecode',
            constraint=models.UniqueConstraint(fields=('document', 'employee_code'), name='docrepo_emp_code_doc_code_uniq'),
        ),
        migrations.AddIndex(
            model_name='indexstate',
            index=models.Index(fields=['is_indexed', 'indexed_at'], name='docrepo_index_state_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancedocument',
            index=models.Index(fields=['insurance_type', 'insurance_subtype'], name='docrepo_ins_type_sub_idx'),
        ),
        migrations.AddConstraint(
            model_name='insurancedocument',
            constraint=models.CheckConstraint(check=models.Q(('coverage_start__isnull', True), ('coverage_end__isnull', True), ('coverage_end__gte', models.F('coverage_start')), _connector='OR'), name='docrepo_ins_coverage_range_chk'),
        ),
        migrations.AddIndex(
            model_name='storageobject',
            index=models.Index(fields=['bucket_name', 'object_key'], name='docrepo_storage_bucket_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='storageobject',
            constraint=models.UniqueConstraint(fields=('bucket_name', 'object_key'), name='docrepo_storage_bucket_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='tregistrodocument',
            index=models.Index(fields=['movement_type', 'effective_date'], name='docrepo_treg_move_date_idx'),
        ),
    ]
