# Generated by Django 5.0.1 on 2026-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docrepo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='correction_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
